### ISSUE TITLE
Add a description to the repository

### ISSUE THREAD

**Issue by derekstavis** [oh-my-fish/theme-clearance#1]
Oh My Fish uses Github API to fetch repository descriptions with `omf describe`. Adding a description to this project would be nice!

**Comment by cseelus** [comment]
Added it to the original repo.

**Comment by derekstavis** [comment]
Oh My Fish uses this repository as install source, and you have admin rights here. Would you mind updating the description here too?

**Comment by cseelus** [comment]
It seems that can only create pull-requests. I have no "Edit-Button" on the "Description" line either, as I have with repositories on Github that have have write access to:

![screen shot 2016-03-24 at 16 18 02](https://cloud.githubusercontent.com/assets/3188392/14021483/00790b48-f1dc-11e5-8a9a-2400ba845bfe.png)

**Comment by bpinto** [comment]
@cseelus

This has been addressed, sorry for the trouble.

**Comment by cseelus** [comment]
Not a problem. I added the description.
