### ISSUE TITLE
Make terminal exactly as in image

### ISSUE THREAD

**Issue by yashshah7197** [oh-my-fish/theme-clearance#2]
How would I edit the colors and fonts in fish to make my shell look exactly as shown in the screenshot? I mean the colors for the commands, text, etc.
I'm using iTerm2 if that's of any help.

**Comment by cseelus** [comment]
The git history for my dotfiles shows that I seem to have used a font called "Lekton" at that time I made the preview screenshot.

The colors I used at that time in my Terminal are the same I use in a [VIM colorscheme of mine that is also called "Clearance"](https://github.com/cseelus/vim-colors-clearance). You can [find them here](https://github.com/cseelus/vim-colors-clearance/blob/master/colors/clearance.vim) (line 9-35).

To edit the colors and fonts for iTerm2 you have to open "Preferences" > "Profiles" > "Name of your currently used profile". There you can set them within the "Colors" and "Text" tabs.

**Comment by yashshah7197** [comment]
Sorry but I don't quite seem to understand. How do I apply them vim color scheme so that my terminal looks exactly as in the preview image?

**Comment by cseelus** [comment]
You can't apply them directly, as the colors of most modern Terminal emulators like iTerm have their own settings. iTerm2 has very sophisticated profiles, where you can customize nearly everything, from aliasing your Fonts to your prefered colors for different types of text to your Window type and in everything in between.

At the time I made the screenshot for the Clearance Fish theme, I used the default Terminal from macOS, whose profiles can't be used by iTerm.

You can copy the hex color codes from the VIM colorscheme I linked above to create an iTerm profile that looks like the screenshot of this repo and maybe post your iTerm profile here for others to use.

(I myself use [a new colorscheme/profile of my own](https://github.com/cseelus/vim-colors-lucid) these days, in fact I use to build me a new one and publish it, every now and then)
