### ISSUE TITLE
What font would you recommend with this theme?

### ISSUE THREAD

**Issue by tleb** [oh-my-fish/theme-clearance#3]
I use [the Hack font](http://sourcefoundry.org/hack/), I love it but I wondered what font you guys are using?

It seems like the arrow character used isn't supported by many fonts.

**Comment by cseelus** [comment]
The font used in the screenshot is [Lekton](https://fonts.google.com/specimen/Lekton), but nowadays I use Roboto Mono.

Generally I can't remember to ever have problems with the arrow char.
